/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package claypi

import java.util.logging.Logger
import java.util.logging.Level

import kotlinx.serialization.*
import kotlinx.serialization.json.Json

import java.io.File

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main(args: Array<String>) {
    val info = loadInfo("../data/bot_info.json")

    embeddedServer(Netty, 8080) {
        install(Routing) {
            get("/") {

            }
        }
    }.start(wait = true)
}
