/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package claypi

import org.litote.kmongo.reactivestreams.*
import org.litote.kmongo.coroutine.*

import java.util.logging.Logger
import java.util.logging.Level

fun kill(name: String) {
    val log = Logger.getLogger(name)
    log.setLevel(Level.SEVERE)
}

fun main(args: Array<String>) {
    // make java logging shut the fuck up
    kill("org.mongodb")
    val client = KMongo.createClient().coroutine
}
